# This file is part of Adblock Plus <https://adblockplus.org/>,
# Copyright (C) 2006-present eyeo GmbH
#
# Adblock Plus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Adblock Plus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Adblock Plus.  If not, see <http://www.gnu.org/licenses/>.
#
# This file specifies how GitLab should run the tests, linting and other checks
# automatically when merge requests are opened. By default, this will all run
# on GitLab provided "shared runners", without further work. However, the tests
# will run more quickly on a "specific runner" if you'd like to set that up.
#
# If you'd like to provision your own specific runners for your fork of the
# repository, you can use these Ansible roles:
#
# https://gitlab.com/eyeo/devops/ansible-role-adblockplus-builder
# https://gitlab.com/eyeo/devops/ansible-role-gitlab-runner


---

image: "registry.gitlab.com/eyeo/docker/adblockplus-ci:node10"

before_script:
  - "[ -z \"$BROWSER_SNAPSHOT_DIR\" ] || mkdir -p $BROWSER_SNAPSHOT_DIR"
  - npm install

tests:
  script:
    - npm test
  variables:
    BROWSER_SNAPSHOT_DIR: "/tmp/browser-snapshots/"
  retry:
    max: 2
    when: stuck_or_timeout_failure

docs:
  script:
    - npm run docs
  artifacts:
    paths:
      - docs/
    expire_in: 3 mos
  retry:
    max: 2
    when: stuck_or_timeout_failure
