# This file is part of Adblock Plus <https://adblockplus.org/>,
# Copyright (C) 2006-present eyeo GmbH
#
# Adblock Plus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Adblock Plus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Adblock Plus.  If not, see <http://www.gnu.org/licenses/>.
#
# NOTE:
# This CI configuration is meant to be run on private runners, which can be
# provisioned with the Ansible roles from
# https://gitlab.com/eyeo/devops/ansible-role-adblockplus-builder and
# https://gitlab.com/eyeo/devops/ansible-role-gitlab-runner

---

tests:
  tags:
    - nodejs
  before_script:
    - mkdir -p .git/info
    - ./ensure_dependencies.py
    - npm install
  script:
    - npm test
